Enable stream Decode/Encode
go-yaml/yaml pull request #163
Opened 2016-03-08 05:11 UTC by jeffjen

The pull request enables user to submit an Reader/Writer to process unbounded YAML stream.

Usage example
```go
// READ from huge yml stream file
r, err := os.Open("thing.yml")
if err != nil {
    panic(err)
}
defer r.Close()

decoder = yaml.NewDecoder(r)
defer decoder.Close()

var thing struct{}
for decoder.Decode(&thing) == nil {
    fmt.Printfln("%#v", stuff)
}
```

```go
// WRITE to output stream
w, err := os.Create("stuff.yml")
if err != nil {
    panic(err)
}
defer w.Close()

encoder := yaml.NewEncoder(w)
defer encoder.Close()

var stuff struct{}
for encoder.Encode(stuff) == nil {
    // Change date or Adjust??
}

```

2016-03-09 13:41 UTC, niemeyer commented
Thanks Jeff.

Can you please have a look at the contributor agreement here and sign if you're comfortable:

 * http://www.ubuntu.com/legal/contributors

It's a non-draconian agreement which is hopefully okay, and may be signed online.

Then, we'll need a few tests and docs, and perhaps some simple tweaks. But the direction is good.

2016-08-17 00:41 UTC, marcosnils commented
Any updates on this?. Looking forward for this functionality.

2016-08-26 18:29 UTC, jeffjen commented
Need help with "contributor agreement".  I don't know if I am clear on that front.

2016-08-26 19:06 UTC, niemeyer commented
@jeffjen Can you please have a look at:

https://www.ubuntu.com/legal/contributors

2016-08-26 19:09 UTC, niemeyer commented
The functionality and the API look reasonable. Would be good to have some conventional comments on the public pieces.

2017-03-26 17:02 UTC, guilhem commented
Gentle ping?

2017-07-21 17:33 UTC, rogpeppe requested changes
This looks like a good start, thanks, but there are some issues that need resolving before this can land, I think.

2017-07-21 17:33 UTC, rogpeppe commented on yamlstream.go
> +	enc.e.finish()
I think that this needs a defer handleErr otherwise it can panic if there's an error when the final bytes are written to the stream.

2017-07-21 17:33 UTC, rogpeppe commented on yamlstream.go
> +type Encoder struct {
doc comment please.

2017-07-21 17:33 UTC, rogpeppe commented on yamlstream.go
> +func (enc *Encoder) Encode(in interface{}) (err error) {
doc comment please.

2017-07-21 17:33 UTC, rogpeppe commented on yamlstream.go
> +func NewDecoder(r io.Reader) *Decoder {
doc comment please.

2017-07-21 17:33 UTC, rogpeppe commented on yamlstream.go
> +func (dec *Decoder) Close() {
I don't think this method is needed - all the destroy method does is zero some memory. I think we can leave the garbage collector to do that.

2017-07-21 17:33 UTC, rogpeppe commented on yamlstream.go
> +func (dec *Decoder) Decode(out interface{}) (err error) {
doc comment please.

2017-07-21 17:33 UTC, rogpeppe commented on yamlstream.go
> +type Decoder struct {
doc comment please.

2017-07-21 17:33 UTC, rogpeppe commented on yamlstream.go
> +func NewEncoder(w io.Writer) *Encoder {
doc comment please.

2017-07-21 17:33 UTC, rogpeppe commented on yamlstream_test.go
> +		c.Assert(value, DeepEquals, v.Interface())
We should be able to use DeepEquals even when the value is a string.

2017-07-21 17:33 UTC, rogpeppe commented on decode.go
> +	p.skip()
I'm not sure we should be calling skip here -  it means that NewDecoder can fail, and I don't think it's a great idea to make that return an error (it's nice if the YAML API mirrors the encoding/json API).

2017-07-21 17:33 UTC, rogpeppe commented on encode.go
> +	e.must(yaml_stream_start_event_initialize(&e.event, yaml_UTF8_ENCODING))
A similar issue applies here to the one in newFileParser. I don't think this should actually write anything until a value is encoded.

2017-07-21 17:33 UTC, rogpeppe commented on yamlstream_test.go
> +package yaml_test
We'd need some Encoder tests too, please.

2017-11-12 17:11 UTC, im-kulikov commented
https://github.com/go-yaml/yaml/pull/288 commits + would fix some issues

2018-03-26 05:47 UTC, niemeyer commented
Implemented in #301 and #306.

2018-03-26 05:47 UTC, closed without merging